'# ── Canonical map matching ───────────────────────────',
'print()',
'print("=" * 55)',
'print("5. Canonical map matching (Custo 2017)")',
'print("=" * 55)',
'',
'try:',
'    from pycrostates.cluster import ModKMeans',
'    from pycrostates.io import ChInfo',
'    import mne',
'',
'    # Load canonical Custo 2017 7-map templates',
'    # Using pycrostates built-in templates',
'    from pycrostates.cluster._utils import _get_cluster_centers',
'    canonical = mne.datasets.fetch_fsaverage(verbose=False)',
'    print("  pycrostates available")',
'except Exception as e:',
'    print("  pycrostates not available: " + str(e))',
'    canonical = None',
'',
'# Manual canonical matching using published channel weights',
'# Custo 2017 Fig 2 — 7 maps on standard 10-20 system',
'# We use spatial correlation to find best match',
'',
'# Load channel info from first available FIF',
'import glob',
'fifs = glob.glob("/projects/swglab/data/DMNELF/derivatives/eeg_preprocessed'
'    '/sub-dmnelf001/ses-dmnelf/eeg/*preproc" + SFREQ_TAG + "_eeg.fif")',
'if fifs:',
'    raw_ref = mne.io.read_raw_fif(fifs[0], preload=False, verbose=False)',
'    ch_names = [ch for ch in raw_ref.ch_names',
'                if "ECG" not in ch.upper()',
'                and ch not in ("TP9","TP10")]',
'    n_ch = len(ch_names)',
'    print("  Channels used for matching: " + str(n_ch))',
'',
'    # Canonical network labels based on Custo 2017',
'    # Key channel signatures (dominant channels per network)',
'    canonical_signatures = {',
'        "DMN":     {"pos": ["Pz","POz","P3","P4","CP1","CP2"],',
'                    "neg": ["Fz","F3","F4","FC1","FC2"]},',
'        "CEN-R":   {"pos": ["F4","FC2","FC6","F8","P4"],',
'                    "neg": ["F3","FC1","FC5","F7","P3"]},',
'        "CEN-L":   {"pos": ["F3","FC1","FC5","F7","P3"],',
'                    "neg": ["F4","FC2","FC6","F8","P4"]},',
'        "VIS":     {"pos": ["Oz","O1","O2","POz","Pz"],',
'                    "neg": ["Fz","Fp1","Fp2","F3","F4"]},',
'        "SOM":     {"pos": ["Cz","C3","C4","CP1","CP2"],',
'                    "neg": ["Oz","O1","O2","Fp1","Fp2"]},',
'        "SAL":     {"pos": ["Fz","FC1","FC2","Cz","F3"],',
'                    "neg": ["Pz","POz","P3","P4","Oz"]},',
'        "AUD":     {"pos": ["T7","T8","C3","C4","F7"],',
'                    "neg": ["Pz","POz","Fz","Fp1","Fp2"]},',
'    }',
'',
'    # Build canonical vectors',
'    def make_canonical_vec(sig, ch_names):',
'        v = np.zeros(len(ch_names))',
'        for ch in sig["pos"]:',
'            if ch in ch_names:',
'                v[ch_names.index(ch)] += 1.0',
'        for ch in sig["neg"]:',
'            if ch in ch_names:',
'                v[ch_names.index(ch)] -= 1.0',
'        n = np.linalg.norm(v)',
'        return v / n if n > 1e-10 else v',
'',
'    canonical_vecs = {',
'        name: make_canonical_vec(sig, ch_names)',
'        for name, sig in canonical_signatures.items()',
'    }',
'',
'    # Correlate each fitted map with each canonical',
'    print()',
'    print("  Map assignments (best canonical match):")',
'    assignments = {}',
'    corr_matrix = np.zeros((N_MICROSTATES, len(canonical_vecs)))',
'    canon_names = list(canonical_vecs.keys())',
'',
'    for k in range(N_MICROSTATES):',
'        t = best_templates[k]',
'        if len(t) != len(ch_names):',
'            t = t[:len(ch_names)]',
'        for j, (cname, cvec) in enumerate(canonical_vecs.items()):',
'            corr_matrix[k,j] = abs(np.corrcoef(t, cvec)[0,1])',
'',
'    # Greedy assignment — highest correlation first',
'    assigned_maps    = set()',
'    assigned_canons  = set()',
'    assignment_list  = []',
'    flat_idx = np.argsort(corr_matrix.ravel())[::-1]',
'    for idx in flat_idx:',
'        k = idx // len(canon_names)',
'        j = idx  % len(canon_names)',
'        if k not in assigned_maps and j not in assigned_canons:',
'            assigned_maps.add(k)',
'            assigned_canons.add(j)',
'            assignment_list.append((k, canon_names[j],',
'                                    corr_matrix[k,j]))',
'    # Sort by map index',
'    assignment_list.sort(key=lambda x: x[0])',
'',
'    label_map = {}',
'    for k, canon, corr in assignment_list:',
'        label_map[k] = canon',
'        print("  MS" + chr(65+k)',
'              + " → " + canon',
'              + "  r=" + "{:.3f}".format(corr))',
'',
'    # Save assignments',
'    import json',
'    assign_path = ms_dir / ("assignments_" + SFREQ_TAG + ".json")',
'    with open(str(assign_path), "w") as f:',
'        json.dump({str(k): v for k,v in label_map.items()}, f, indent=2)',
'    print()',
'    print("  Assignments saved: " + str(assign_path))',
'',
'print()',
'print("DONE  " + SFREQ_TAG)',